# User config for coreos-pxe-provision

# Name of the host interface to bind the DNS/DHCP/TFTP services to:
interface: eth0
# The IP address of the docker server:
public_ip: 10.99.0.2

# Upstream DNS servers:
dns:
  - 1.0.0.1
  - 1.1.1.1

# DHCP options:
dhcp:
  range_start: 10.99.0.10
  range_end: 10.99.0.253
  domain: provision.lan.rymcg.tech
  gateway: 10.99.0.1

menu_entries:
  - message: "Auto-Install Fedora CoreOS 30 (THIS WILL WIPE DRIVES!)"
    kernel: coreos30/images/vmlinuz
    initrd: coreos30/images/initramfs.img
    image: fedora-coreos-30.20190716.1-metal.raw.xz
    
auto_install:
  enabled: false
  entry: 0

ssh_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPuwf6ID+p8LAYBORP9HndBOhlKBDRhknVtYMEim8eflQDD9Uw0tMoEbHFemMvkZl9lbUatNlq7twSnumjwUv23LX48h9sn4enoo8D8xtE7tYh0jIRmyIG/fDMRLXGT+k7rP4Piky7j8kYh9mNHKmEwL4El1Fqe/R1xoHF6NyXKXxug3nCksMwlvhfBUPDo/zktxQ1Ddy34oAwS3Uo2/aur9lGJBqYEaUyHEBhbnq5Nm1xMN8ZWC3GQqjFlS8m6zu78P2OLGTL1o2vwbAyVaarO6tK6KUcWbxqmjK1igcZTJL0OLltRIvZn/4ELpPXzNl7spGAt5ylwJSAZP75zZ7F ryan@Maldekian

isos:
  fedora-coreos-30.20190725.0-installer.iso:
    url: https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20190725.0/x86_64/fedora-coreos-30.20190725.0-installer.iso
    destination: /data/isos/fedora-coreos-30.20190725.0-installer.iso
    mount: /data/coreos30
    sha256: 77f484a3ba2f5891c55301f0bc5278b795d5ae278f8a5b2003bcdaf100457751
images:
  fedora-coreos-30.20190716.1-metal.raw.xz:
    url: https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20190725.0/x86_64/fedora-coreos-30.20190725.0-metal.raw.xz
    destination: /data/images/fedora-coreos-30.20190716.1-metal.raw.xz
    sha256: f39ea47b716d946adb830d9d1121d0fadf57890fd6909b1d57933f37ad75c8da
    
clients:
  be-e8-58-c1-85-f8:
    hostname: bios1
    interface: ens18
    install_dev: sda
    ip_address: 10.99.0.3
