### This is the *default* config file that gets baked into the container build.
### You probably don't need to edit this file unless you want to customize the docker image.
### Instead, map your own config via a docker volume at runtime:
###     -v your_config.yaml:/config/config.yaml
### The User config maps into the container at /config/config.yaml
### It will be merged with /config/default.yaml (that's this file.)

# Template map -
#   This is a list of all the config template files and the path to
#   render them to. Example:
#
#  template_map:
#    my_config.mako: /etc/my_app/my_config.cfg
#    second_config.mako: /etc/my_other_app/name.conf
#
template_map:
 dnsmasq.conf.mako: /etc/dnsmasq.conf
 dhcp_hosts.txt.mako: /etc/dhcp_hosts.txt
 nginx.conf.mako: /etc/nginx/nginx.conf
 pxelinux_default.cfg.mako: /data/pxelinux.cfg/default

interface: eth0
http_port: 8000

dhcp:
  uefi_boot: debian-installer/amd64/bootnetx64.efi
  bios_boot: pxelinux.0
  netmask: 255.255.255.0
  lease_time: 24h

dns:
  - 1.0.0.1
  - 1.1.1.1

clients: {}

client_defaults:
  hostname: coreos
  enabled: false
  interface: ens18
  cidr: 24
  install_dev: sda
  vga: false
  username: core
  password: null

images: {}
isos: {}

auto_install:
  enabled: false
  entry: 0
  timeout: 5
