FROM ubuntu:18.04

ARG DOCTL_VERSION
ARG GOLANG_VERSION
ENV DOCTL_VERSION=$DOCTL_VERSION
ENV GOLANG_VERSION=$GOLANG_VERSION
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /app

RUN apt-get update -y && \
    apt-get install -y git curl jq && \
    curl -L https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64 > /usr/bin/yq && \
    chmod 755 /usr/bin/yq && \
    curl -sLSf https://get.k3sup.dev | sh && \
    curl -L https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz  | tar xz -C /usr/bin && \
    apt-get install -y --no-install-recommends g++ gcc libc6-dev make pkg-config && \
    curl -SL https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz | tar xvz -C /usr/local && \
    mkdir -p $GOPATH && \
    go get github.com/spf13/cobra/cobra

